import "server-only";
import { kv } from "./kv";
import type { Biodata, User } from "./types";

/**
 * Sample profiles so the site isn't empty while real families join. They use drawn
 * portraits (public/samples), carry `sample: true`, show a "Sample" tag everywhere,
 * and can't receive interests. They have no phone number, so nobody can log in as them.
 *
 * Set SANGAM_SAMPLE_PROFILES=off in Vercel to remove them.
 */

type Seed = Omit<Biodata, "userId" | "gender" | "photos" | "published" | "updatedAt" | "sample">;

const BRIDES: Seed[] = [
  { fullName: "Ananya Sharma", dob: "1999-04-12", height: "5 ft 4 in (163 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Hindi", community: "Marwari", caste: "Agrawal", gotra: "Garg", education: "MBA", college: "IIM Indore", sector: "Private", occupation: "HR Manager", employer: "Infosys", income: "₹12–18 lakh", workCity: "Indore", fatherName: "Ramesh Sharma", fatherOccupation: "Business", motherName: "Meena Sharma", motherOccupation: "Homemaker", brothers: "1 younger", familyType: "Nuclear family", nativePlace: "Jhunjhunu, Rajasthan", city: "Indore", state: "Madhya Pradesh", diet: "Vegetarian", manglik: "No", about: "I work in HR, read a lot and cook on Sundays. Close to my family and looking for someone who is too.", hobbies: "Reading, cooking, Kathak", expectations: "Educated, kind and family-oriented. Settled in India." },
  { fullName: "Priyanka Iyer", dob: "1998-11-02", height: "5 ft 3 in (160 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Tamil", community: "Tamil Brahmin", caste: "Iyer", gotra: "Kaushika", education: "M.Tech", college: "Anna University", sector: "Private", occupation: "Data Scientist", employer: "Zoho", income: "₹18–25 lakh", workCity: "Chennai", fatherName: "S. Ramanathan", fatherOccupation: "Retired, Indian Bank", motherName: "Lakshmi Ramanathan", motherOccupation: "Teacher", sisters: "1 elder, married", familyType: "Nuclear family", nativePlace: "Thanjavur", city: "Chennai", state: "Tamil Nadu", diet: "Vegetarian", rashi: "Kanya (Virgo)", about: "Carnatic music learner, weekend baker and a data nerd at work.", hobbies: "Veena, baking, trekking", expectations: "Someone curious and grounded who respects both families." },
  { fullName: "Sneha Patil", dob: "1997-07-21", height: "5 ft 5 in (165 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Marathi", community: "Maratha", caste: "Patil", education: "MBBS", college: "BJ Medical College, Pune", sector: "Professional (Doctor, CA, Lawyer)", occupation: "Doctor", employer: "Ruby Hall Clinic", income: "₹12–18 lakh", workCity: "Pune", fatherName: "Suresh Patil", fatherOccupation: "Farmer and business", motherName: "Asha Patil", motherOccupation: "Homemaker", brothers: "1 elder, married", familyType: "Joint family", nativePlace: "Satara", city: "Pune", state: "Maharashtra", diet: "Non-vegetarian", about: "Paediatrician who loves long drives to the ghats and old Marathi songs.", hobbies: "Travel, music, gardening", expectations: "A doctor or professional from a warm, supportive family." },
  { fullName: "Kavya Reddy", dob: "2000-01-15", height: "5 ft 2 in (157 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Telugu", community: "Reddy", caste: "Reddy", education: "B.Tech", college: "JNTU Hyderabad", sector: "Private", occupation: "Software Engineer", employer: "Microsoft", income: "₹25–40 lakh", workCity: "Hyderabad", fatherName: "Venkat Reddy", fatherOccupation: "Real estate", motherName: "Padma Reddy", motherOccupation: "Homemaker", brothers: "1 younger, studying", familyType: "Nuclear family", nativePlace: "Nellore", city: "Hyderabad", state: "Telangana", diet: "Non-vegetarian", about: "Engineer by day, Kuchipudi dancer by evening. I love my family's biryani Sundays.", hobbies: "Kuchipudi, badminton, movies", expectations: "Well-settled, easy-going and fun to be around." },
  { fullName: "Riya Mehta", dob: "1998-09-08", height: "5 ft 4 in (163 cm)", maritalStatus: "Never married", religion: "Jain", motherTongue: "Gujarati", community: "Gujarati", caste: "Jain", education: "CA", college: "ICAI", sector: "Professional (Doctor, CA, Lawyer)", occupation: "Chartered Accountant", employer: "Deloitte", income: "₹18–25 lakh", workCity: "Ahmedabad", fatherName: "Nitin Mehta", fatherOccupation: "Textile business", motherName: "Hema Mehta", motherOccupation: "Homemaker", sisters: "1 younger", familyType: "Joint family", nativePlace: "Surat", city: "Ahmedabad", state: "Gujarat", diet: "Jain vegetarian", about: "CA who still makes time for garba every Navratri.", hobbies: "Garba, sketching, travel", expectations: "Jain family, vegetarian, business or professional." },
  { fullName: "Simran Kaur", dob: "1999-02-27", height: "5 ft 6 in (168 cm)", maritalStatus: "Never married", religion: "Sikh", motherTongue: "Punjabi", community: "Jat Sikh", caste: "Jat", education: "M.Sc", college: "Punjab Agricultural University", sector: "Government", occupation: "Assistant Professor", employer: "PAU Ludhiana", income: "₹8–12 lakh", workCity: "Ludhiana", fatherName: "Gurmeet Singh", fatherOccupation: "Farmer", motherName: "Harjeet Kaur", motherOccupation: "Homemaker", brothers: "2 elder, married", familyType: "Joint family", nativePlace: "Moga", city: "Ludhiana", state: "Punjab", diet: "Vegetarian", about: "I teach plant science, sing in the gurdwara and cannot resist makki di roti.", hobbies: "Singing, phulkari embroidery", expectations: "Sikh family, well educated, respectful and humble." },
  { fullName: "Pooja Gupta", dob: "1997-12-19", height: "5 ft 3 in (160 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Hindi", community: "Vaishya", caste: "Gupta", gotra: "Goyal", education: "B.Com", college: "Lucknow University", sector: "Government", occupation: "Bank Officer", employer: "State Bank of India", income: "₹8–12 lakh", workCity: "Lucknow", fatherName: "Anil Gupta", fatherOccupation: "Shop owner", motherName: "Sunita Gupta", motherOccupation: "Homemaker", brothers: "1 younger", sisters: "1 elder, married", familyType: "Joint family", nativePlace: "Lucknow", city: "Lucknow", state: "Uttar Pradesh", diet: "Vegetarian", manglik: "Anshik (partial)", about: "Simple, cheerful and a big fan of Lucknow's food lanes.", hobbies: "Cooking, rangoli, bhajans", expectations: "Government job or business, from a traditional family." },
  { fullName: "Aishwarya Nair", dob: "1998-05-30", height: "5 ft 5 in (165 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Malayalam", community: "Nair", caste: "Nair", education: "MA", college: "University of Kerala", sector: "Private", occupation: "Content Strategist", employer: "UST", income: "₹8–12 lakh", workCity: "Kochi", fatherName: "Gopinath Nair", fatherOccupation: "Retired, KSEB", motherName: "Radha Nair", motherOccupation: "Teacher", familyType: "Nuclear family", nativePlace: "Thrissur", city: "Kochi", state: "Kerala", diet: "Non-vegetarian", about: "Writer, Mohiniyattam learner and a monsoon person.", hobbies: "Writing, dance, photography", expectations: "Open-minded, well read, and fond of travel." },
  { fullName: "Neha Joshi", dob: "2000-06-11", height: "5 ft 2 in (157 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Rajasthani", community: "Brahmin", caste: "Joshi", gotra: "Bharadwaj", education: "B.Arch", college: "MNIT Jaipur", sector: "Private", occupation: "Architect", employer: "Studio Lotus", income: "₹5–8 lakh", workCity: "Jaipur", fatherName: "Mahesh Joshi", fatherOccupation: "Lecturer", motherName: "Kiran Joshi", motherOccupation: "Homemaker", brothers: "1 elder", familyType: "Nuclear family", nativePlace: "Ajmer", city: "Jaipur", state: "Rajasthan", diet: "Vegetarian", manglik: "No", about: "Architect who sketches havelis on weekends.", hobbies: "Sketching, heritage walks", expectations: "Creative, supportive and from a cultured family." },
  { fullName: "Ayesha Khan", dob: "1999-10-03", height: "5 ft 4 in (163 cm)", maritalStatus: "Never married", religion: "Muslim", motherTongue: "Urdu", community: "Sunni", caste: "Pathan", education: "M.Pharm", college: "Barkatullah University", sector: "Private", occupation: "Pharmacist", employer: "Sun Pharma", income: "₹5–8 lakh", workCity: "Bhopal", fatherName: "Salim Khan", fatherOccupation: "Government service", motherName: "Nasreen Khan", motherOccupation: "Homemaker", sisters: "1 younger", familyType: "Nuclear family", nativePlace: "Bhopal", city: "Bhopal", state: "Madhya Pradesh", diet: "Non-vegetarian", about: "Pharmacist, calligraphy lover and the family's official Eid host.", hobbies: "Calligraphy, poetry, baking", expectations: "Educated, respectful and religiously grounded." },
  { fullName: "Tanvi Deshmukh", dob: "1998-03-17", height: "5 ft 6 in (168 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Marathi", community: "Deshastha Brahmin", caste: "Brahmin", education: "LLB", college: "ILS Law College", sector: "Professional (Doctor, CA, Lawyer)", occupation: "Advocate", employer: "Bombay High Court (Nagpur bench)", income: "₹8–12 lakh", workCity: "Nagpur", fatherName: "Vijay Deshmukh", fatherOccupation: "Advocate", motherName: "Smita Deshmukh", motherOccupation: "Professor", familyType: "Nuclear family", nativePlace: "Amravati", city: "Nagpur", state: "Maharashtra", diet: "Vegetarian", about: "Lawyer who argues less at home than in court, promise.", hobbies: "Debating, cycling, theatre", expectations: "Independent thinker, professional, based in Maharashtra." },
  { fullName: "Megha Bansal", dob: "1996-08-25", height: "5 ft 5 in (165 cm)", maritalStatus: "Divorced", religion: "Hindu", motherTongue: "Hindi", community: "Agrawal", caste: "Bansal", gotra: "Bansal", education: "MBA", college: "FMS Delhi", sector: "Business / Self-employed", occupation: "Boutique owner", employer: "Own label", income: "₹12–18 lakh", workCity: "Delhi", fatherName: "Rajesh Bansal", fatherOccupation: "Business", motherName: "Alka Bansal", motherOccupation: "Homemaker", brothers: "1 younger", familyType: "Joint family", nativePlace: "Hisar", city: "Delhi", state: "Delhi", diet: "Vegetarian", about: "I run my own ethnic-wear label and believe in second chances and honest conversations.", hobbies: "Design, yoga, travel", expectations: "Mature, understanding and settled in Delhi NCR." },
];

const GROOMS: Seed[] = [
  { fullName: "Rohan Agrawal", dob: "1995-06-18", height: "5 ft 10 in (178 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Hindi", community: "Marwari", caste: "Agrawal", gotra: "Mittal", education: "B.Tech", college: "SGSITS, Indore", sector: "Business / Self-employed", occupation: "Business owner", employer: "Family textile business", income: "₹25–40 lakh", workCity: "Indore", fatherName: "Sunil Agrawal", fatherOccupation: "Business", motherName: "Rekha Agrawal", motherOccupation: "Homemaker", sisters: "1 elder, married", familyType: "Joint family", nativePlace: "Churu, Rajasthan", city: "Indore", state: "Madhya Pradesh", diet: "Vegetarian", manglik: "No", about: "Running our family textile business with new ideas. Cricket every Sunday morning.", hobbies: "Cricket, road trips, cooking", expectations: "Educated, family-oriented and cheerful." },
  { fullName: "Arjun Menon", dob: "1994-09-09", height: "5 ft 11 in (180 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Malayalam", community: "Nair", caste: "Menon", education: "M.Tech", college: "IIT Madras", sector: "Private", occupation: "Product Manager", employer: "Flipkart", income: "₹40–60 lakh", workCity: "Bengaluru", fatherName: "Krishnan Menon", fatherOccupation: "Retired, ISRO", motherName: "Sreedevi Menon", motherOccupation: "Doctor", familyType: "Nuclear family", nativePlace: "Palakkad", city: "Bengaluru", state: "Karnataka", diet: "Non-vegetarian", about: "Product manager, amateur drummer and a Kerala-sadya loyalist.", hobbies: "Drums, running, football", expectations: "Independent, warm and ambitious." },
  { fullName: "Karan Malhotra", dob: "1993-12-05", height: "6 ft 0 in (183 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Punjabi", community: "Khatri", caste: "Khatri", education: "MBA", college: "IIM Lucknow", sector: "Private", occupation: "Investment Banker", employer: "Kotak Mahindra Bank", income: "₹40–60 lakh", workCity: "Mumbai", fatherName: "Ashok Malhotra", fatherOccupation: "Chartered Accountant", motherName: "Neelam Malhotra", motherOccupation: "Homemaker", brothers: "1 younger", familyType: "Nuclear family", nativePlace: "Amritsar", city: "Delhi", state: "Delhi", diet: "Non-vegetarian", about: "Banker in Mumbai, Delhi boy at heart. I cook a mean rajma chawal.", hobbies: "Squash, cooking, music", expectations: "Working professional, fun-loving and grounded." },
  { fullName: "Vikram Singh Rathore", dob: "1994-03-22", height: "6 ft 1 in (185 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Rajasthani", community: "Rajput", caste: "Rathore", education: "BA", college: "JNVU Jodhpur", sector: "Government", occupation: "Army Officer (Captain)", employer: "Indian Army", income: "₹12–18 lakh", workCity: "Jodhpur", fatherName: "Col. Mahendra Singh Rathore", fatherOccupation: "Retired, Indian Army", motherName: "Kanchan Kanwar", motherOccupation: "Homemaker", sisters: "1 elder, married", familyType: "Joint family", nativePlace: "Jodhpur", city: "Jodhpur", state: "Rajasthan", diet: "Non-vegetarian", about: "Third-generation army officer. Horse riding, polo and old ghazals.", hobbies: "Horse riding, polo, ghazals", expectations: "Confident, adaptable to army life, from a Rajput family." },
  { fullName: "Aditya Kulkarni", dob: "1996-01-10", height: "5 ft 9 in (175 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Marathi", community: "Deshastha Brahmin", caste: "Kulkarni", education: "B.E.", college: "COEP Pune", sector: "Private", occupation: "Software Engineer", employer: "Persistent Systems", income: "₹18–25 lakh", workCity: "Pune", fatherName: "Shrikant Kulkarni", fatherOccupation: "Professor", motherName: "Vaishali Kulkarni", motherOccupation: "Bank officer", familyType: "Nuclear family", nativePlace: "Sangli", city: "Pune", state: "Maharashtra", diet: "Vegetarian", rashi: "Simha (Leo)", about: "Engineer who plays the harmonium at every family gathering.", hobbies: "Harmonium, trekking, chess", expectations: "Maharashtrian, working, with a love for music." },
  { fullName: "Harpreet Singh", dob: "1995-08-14", height: "5 ft 11 in (180 cm)", maritalStatus: "Never married", religion: "Sikh", motherTongue: "Punjabi", community: "Jat Sikh", caste: "Jat", education: "MBA", college: "Punjab University", sector: "Business / Self-employed", occupation: "Agri-business owner", employer: "Own business", income: "₹25–40 lakh", workCity: "Amritsar", fatherName: "Balwinder Singh", fatherOccupation: "Farmer", motherName: "Kulwinder Kaur", motherOccupation: "Homemaker", sisters: "1 younger", familyType: "Joint family", nativePlace: "Tarn Taran", city: "Amritsar", state: "Punjab", diet: "Vegetarian", about: "Running a modern dairy and cold-storage business. Bhangra is non-negotiable at weddings.", hobbies: "Bhangra, kabaddi, travel", expectations: "Sikh girl, educated, who values family." },
  { fullName: "Siddharth Jain", dob: "1995-05-02", height: "5 ft 8 in (173 cm)", maritalStatus: "Never married", religion: "Jain", motherTongue: "Gujarati", community: "Jain", caste: "Oswal", education: "CA", college: "ICAI", sector: "Professional (Doctor, CA, Lawyer)", occupation: "Chartered Accountant", employer: "Own practice", income: "₹25–40 lakh", workCity: "Mumbai", fatherName: "Mahendra Jain", fatherOccupation: "Diamond business", motherName: "Kusum Jain", motherOccupation: "Homemaker", brothers: "1 elder, married", familyType: "Joint family", nativePlace: "Palanpur", city: "Mumbai", state: "Maharashtra", diet: "Jain vegetarian", about: "CA with my own practice. Paryushan fasts and Sunday badminton.", hobbies: "Badminton, reading, travel", expectations: "Jain, vegetarian, educated and cheerful." },
  { fullName: "Rahul Verma", dob: "1994-10-29", height: "5 ft 8 in (173 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Hindi", community: "Kayastha", caste: "Srivastava", education: "M.Tech", college: "IIT Kanpur", sector: "Government", occupation: "Assistant Engineer", employer: "UP PWD", income: "₹8–12 lakh", workCity: "Kanpur", fatherName: "Dinesh Verma", fatherOccupation: "Retired, Railways", motherName: "Asha Verma", motherOccupation: "Teacher", sisters: "1 elder, married", familyType: "Nuclear family", nativePlace: "Kanpur", city: "Kanpur", state: "Uttar Pradesh", diet: "Vegetarian", manglik: "No", about: "Government engineer, weekend poet and a devoted chai drinker.", hobbies: "Poetry, cricket, gardening", expectations: "Simple, educated girl from a good family." },
  { fullName: "Nikhil Reddy", dob: "1995-02-07", height: "5 ft 10 in (178 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Telugu", community: "Reddy", caste: "Reddy", education: "MS (USA)", college: "Purdue University", sector: "Private", occupation: "Senior Engineer", employer: "Google", income: "Above ₹1 crore", workCity: "Hyderabad", fatherName: "Srinivas Reddy", fatherOccupation: "Doctor", motherName: "Sujatha Reddy", motherOccupation: "Doctor", brothers: "1 younger", familyType: "Nuclear family", nativePlace: "Guntur", city: "Hyderabad", state: "Telangana", diet: "Non-vegetarian", about: "Back in Hyderabad after years in the US. Weekend chef and tennis fan.", hobbies: "Tennis, cooking, photography", expectations: "Educated, independent and close to family." },
  { fullName: "Imran Qureshi", dob: "1994-07-16", height: "5 ft 9 in (175 cm)", maritalStatus: "Never married", religion: "Muslim", motherTongue: "Urdu", community: "Sunni", caste: "Qureshi", education: "MBBS, MD", college: "KGMU Lucknow", sector: "Professional (Doctor, CA, Lawyer)", occupation: "Doctor (Physician)", employer: "Medanta Lucknow", income: "₹18–25 lakh", workCity: "Lucknow", fatherName: "Javed Qureshi", fatherOccupation: "Business", motherName: "Shabana Qureshi", motherOccupation: "Homemaker", sisters: "2 elder, married", familyType: "Joint family", nativePlace: "Lucknow", city: "Lucknow", state: "Uttar Pradesh", diet: "Non-vegetarian", about: "Physician, Urdu poetry reader and a biryani loyalist.", hobbies: "Poetry, cricket, travel", expectations: "Educated, kind and family-minded." },
  { fullName: "Varun Iyer", dob: "1996-04-04", height: "5 ft 9 in (175 cm)", maritalStatus: "Never married", religion: "Hindu", motherTongue: "Tamil", community: "Tamil Brahmin", caste: "Iyer", gotra: "Vadhula", education: "CA", college: "ICAI", sector: "Private", occupation: "Finance Manager", employer: "TVS Motors", income: "₹18–25 lakh", workCity: "Chennai", fatherName: "V. Subramaniam", fatherOccupation: "Retired, LIC", motherName: "Meenakshi Subramaniam", motherOccupation: "Homemaker", familyType: "Nuclear family", nativePlace: "Kumbakonam", city: "Chennai", state: "Tamil Nadu", diet: "Vegetarian", rashi: "Tula (Libra)", about: "Finance manager and mridangam player. Filter coffee, always.", hobbies: "Mridangam, cricket, quizzing", expectations: "Tamil Brahmin, working, fond of music." },
  { fullName: "Saurabh Maheshwari", dob: "1993-11-20", height: "5 ft 10 in (178 cm)", maritalStatus: "Widowed", religion: "Hindu", motherTongue: "Marwari", community: "Marwari", caste: "Maheshwari", gotra: "Rathi", education: "B.Com", college: "MLSU Udaipur", sector: "Business / Self-employed", occupation: "Business owner", employer: "Family marble business", income: "₹40–60 lakh", workCity: "Bhilwara", fatherName: "Govind Maheshwari", fatherOccupation: "Business", motherName: "Shanta Maheshwari", motherOccupation: "Homemaker", brothers: "1 elder, married", familyType: "Joint family", nativePlace: "Bhilwara", city: "Bhilwara", state: "Rajasthan", diet: "Vegetarian", about: "Run our marble business. Lost my wife two years ago and I'm ready to start again with the family's blessing.", hobbies: "Temple visits, cricket, travel", expectations: "Understanding, mature and from a Marwari family." },
];

const MARKER = "samples:v1";

function toBiodata(seed: Seed, i: number, gender: "male" | "female"): Biodata {
  const kind = gender === "female" ? "bride" : "groom";
  const n = String(i + 1).padStart(2, "0");
  return {
    ...seed,
    userId: `sample-${kind}-${n}`,
    gender,
    photos: [`/samples/${kind}-${n}.svg`],
    published: true,
    sample: true,
    // older than any real profile, so real families always appear first
    updatedAt: Date.UTC(2026, 0, 1) + i * 3600_000 + (gender === "female" ? 0 : 1800_000),
  };
}

export function sampleBiodatas() {
  return [...BRIDES.map((s, i) => toBiodata(s, i, "female")), ...GROOMS.map((s, i) => toBiodata(s, i, "male"))];
}

/** Adds the sample profiles once, or removes them when SANGAM_SAMPLE_PROFILES=off. */
export async function ensureSamples() {
  const db = kv();
  const seeded = await db.get(MARKER);
  if (process.env.SANGAM_SAMPLE_PROFILES === "off") {
    if (seeded) {
      for (const b of sampleBiodatas()) {
        await db.zrem("bios:pub", b.userId);
        await db.del(`bio:${b.userId}`, `user:${b.userId}`);
      }
      await db.del(MARKER);
    }
    return;
  }
  if (seeded) return;
  for (const b of sampleBiodatas()) {
    const user: User = {
      id: b.userId,
      name: b.fullName ?? "Sample",
      phone: "",
      gender: b.gender,
      createdFor: "Myself",
      passHash: "sample-profile-no-login",
      createdAt: b.updatedAt,
    };
    await db.set(`user:${b.userId}`, JSON.stringify(user));
    await db.set(`bio:${b.userId}`, JSON.stringify(b));
    await db.zadd("bios:pub", b.updatedAt, b.userId);
  }
  await db.set(MARKER, String(Date.now()));
}
